/**
 * Ícone próprio para cada uma das 361 magias do Livro do Jogador (cap. 11), escolhido
 * pelo efeito da magia. Módulo carregado sob demanda por `SpellIcon` para não pesar
 * no bundle inicial da ficha. Gerado a partir do catálogo `spells-book-catalog`.
 */
import type { IconType } from "react-icons";
import {
  GiAcidBlob,
  GiAcidTube,
  GiAllSeeingEye,
  GiAnchor,
  GiAngelOutfit,
  GiAngelWings,
  GiAngryEyes,
  GiAnvil,
  GiAnvilImpact,
  GiArrowsShield,
  GiAstronautHelmet,
  GiAura,
  GiBeamsAura,
  GiBearHead,
  GiBerriesBowl,
  GiBigWave,
  GiBlindfold,
  GiBoltEye,
  GiBoltSpellCast,
  GiBookAura,
  GiBrain,
  GiBrainDump,
  GiBrainFreeze,
  GiBrainLeak,
  GiBrandyBottle,
  GiBread,
  GiBreakingChain,
  GiBrokenShield,
  GiBrokenSkull,
  GiBubbleField,
  GiBubbles,
  GiBurningDot,
  GiCage,
  GiCampingTent,
  GiCancel,
  GiCandleFlame,
  GiCandleLight,
  GiCape,
  GiCastle,
  GiChainLightning,
  GiChainedHeart,
  GiCharm,
  GiChemicalBolt,
  GiCircleCage,
  GiCircleSparks,
  GiClawString,
  GiCoffin,
  GiCompass,
  GiConversation,
  GiCrackedMask,
  GiCrossShield,
  GiCrossedBones,
  GiCrossedChains,
  GiCrossedSwords,
  GiCrownedSkull,
  GiCrystalBall,
  GiCrystalEye,
  GiCrystalGrowth,
  GiCurlingVines,
  GiCursedStar,
  GiDeathJuice,
  GiDeathSkull,
  GiDeathZone,
  GiDesert,
  GiDisintegrate,
  GiDna1,
  GiDogHouse,
  GiDoorway,
  GiDoubleFaceMask,
  GiDragonHead,
  GiDread,
  GiDreadSkull,
  GiDreamCatcher,
  GiDrippingKnife,
  GiDrippingStar,
  GiDrippingSword,
  GiDualityMask,
  GiDustCloud,
  GiEarthCrack,
  GiEclipse,
  GiEgyptianBird,
  GiElectricalResistance,
  GiEncirclement,
  GiEnergyShield,
  GiEntMouth,
  GiEvilEyes,
  GiEyeShield,
  GiEyeTarget,
  GiEyeball,
  GiFairy,
  GiFairyWand,
  GiFalling,
  GiFeather,
  GiFeatheredWing,
  GiFireDash,
  GiFireRay,
  GiFireRing,
  GiFireShield,
  GiFireSilhouette,
  GiFireWave,
  GiFireball,
  GiFireflake,
  GiFirewall,
  GiFlame,
  GiFlameSpin,
  GiFlameTunnel,
  GiFlamer,
  GiFlamingTrident,
  GiFloatingCrystal,
  GiFloatingGhost,
  GiFloatingPlatforms,
  GiFog,
  GiFootprint,
  GiFrogPrince,
  GiFrozenOrb,
  GiFruitBowl,
  GiGhost,
  GiGhostAlly,
  GiGloves,
  GiGlowingArtifact,
  GiGrapple,
  GiGraveFlowers,
  GiHand,
  GiHandcuffs,
  GiHealing,
  GiHealingShield,
  GiHealthCapsule,
  GiHealthDecrease,
  GiHealthIncrease,
  GiHealthNormal,
  GiHealthPotion,
  GiHeartArmor,
  GiHeartBattery,
  GiHeartBeats,
  GiHeartPlus,
  GiHeartWings,
  GiHiveMind,
  GiHolosphere,
  GiHolyGrail,
  GiHolyOak,
  GiHolySymbol,
  GiHolyWater,
  GiHood,
  GiHorseHead,
  GiHuntingHorn,
  GiIceBolt,
  GiIceBomb,
  GiIceCube,
  GiIceSpellCast,
  GiIciclesAura,
  GiImpLaugh,
  GiImprisoned,
  GiInsectJaws,
  GiInvisible,
  GiInvisibleFace,
  GiIronMask,
  GiJumpAcross,
  GiJusticeStar,
  GiKnightBanner,
  GiKnockout,
  GiLaserBurst,
  GiLaurelCrown,
  GiLibertyWing,
  GiLifeBar,
  GiLifeInTheBalance,
  GiLifeSupport,
  GiLightBulb,
  GiLightningShield,
  GiLightningStorm,
  GiLightningTrio,
  GiLips,
  GiLockedChest,
  GiLockedFortress,
  GiMagicAxe,
  GiMagicGate,
  GiMagicHat,
  GiMagicLamp,
  GiMagicPalm,
  GiMagicPortal,
  GiMagicPotion,
  GiMagicShield,
  GiMagicSwirl,
  GiMagickTrick,
  GiMagnifyingGlass,
  GiManacles,
  GiMaze,
  GiMeal,
  GiMedicines,
  GiMetalBar,
  GiMeteorImpact,
  GiMirrorMirror,
  GiMisdirection,
  GiMissileSwarm,
  GiMoebiusTriangle,
  GiMoon,
  GiMoonBats,
  GiMuscleUp,
  GiMushroomsCluster,
  GiMusicalNotes,
  GiNestedHearts,
  GiNightVision,
  GiOakLeaf,
  GiOilySpiral,
  GiOnTarget,
  GiOppositeHearts,
  GiOwl,
  GiPadlock,
  GiPaperLantern,
  GiPawHeart,
  GiPeaceDove,
  GiPentagramRose,
  GiPineTree,
  GiPlantsAndAnimals,
  GiPlasmaBolt,
  GiPointing,
  GiPoison,
  GiPoisonBottle,
  GiPoisonCloud,
  GiPoisonGas,
  GiPortal,
  GiPotionOfMadness,
  GiPrayer,
  GiPrayerBeads,
  GiPrayingMantis,
  GiPrism,
  GiPsychicWaves,
  GiPuppet,
  GiQuakeStomp,
  GiQuillInk,
  GiQuiver,
  GiRadialBalance,
  GiRainbowStar,
  GiRaiseSkeleton,
  GiRaiseZombie,
  GiRegeneration,
  GiResize,
  GiReturnArrow,
  GiRingedPlanet,
  GiRingingBell,
  GiRockGolem,
  GiRopeCoil,
  GiRun,
  GiRuneStone,
  GiSandstorm,
  GiScales,
  GiScreaming,
  GiScrollQuill,
  GiScrollUnfurled,
  GiSecretDoor,
  GiSemiClosedEye,
  GiShadowFollower,
  GiShakingHands,
  GiShamblingZombie,
  GiSharpLips,
  GiShatteredGlass,
  GiShield,
  GiShieldReflect,
  GiShiningHeart,
  GiShintoShrineMirror,
  GiSilence,
  GiSittingDog,
  GiSkeletalHand,
  GiSkullCrack,
  GiSkullSignet,
  GiSkullWithSyringe,
  GiSleepy,
  GiSlippers,
  GiSmokeBomb,
  GiSnail,
  GiSnowing,
  GiSnowman,
  GiSoundWaves,
  GiSparkSpirit,
  GiSparkles,
  GiSpectre,
  GiSpeedometer,
  GiSpiderAlt,
  GiSpiderWeb,
  GiSpikedHalo,
  GiSpikedWall,
  GiSpinningBlades,
  GiSpiralArrow,
  GiSpiralBloom,
  GiSpiralLollipop,
  GiSpiralShell,
  GiSplitBody,
  GiSpottedBug,
  GiSprout,
  GiSpyglass,
  GiStandingPotion,
  GiStarFormation,
  GiStarStruck,
  GiStarSwirl,
  GiStoneBlock,
  GiStoneBust,
  GiStonePile,
  GiStoneTablet,
  GiStoneTower,
  GiStoneWall,
  GiStonedSkull,
  GiStopSign,
  GiStopwatch,
  GiStrikingArrows,
  GiSun,
  GiSunCloud,
  GiSunPriest,
  GiSunRadiations,
  GiSunSpear,
  GiSunbeams,
  GiSunrise,
  GiSupersonicArrow,
  GiSwirlString,
  GiSwordBreak,
  GiTalk,
  GiTargetArrows,
  GiTelepathy,
  GiTeleport,
  GiTemplarShield,
  GiTempleGate,
  GiTentacleStrike,
  GiTentaclesBarrier,
  GiTheaterCurtains,
  GiThirdEye,
  GiThornHelix,
  GiThornedArrow,
  GiThornyVine,
  GiThreeBurningBalls,
  GiThrownDaggers,
  GiThunderStruck,
  GiTimeTrap,
  GiTombstone,
  GiTornado,
  GiTransform,
  GiTreasureMap,
  GiTreeDoor,
  GiTreeFace,
  GiTreeGrowth,
  GiUnlocking,
  GiUnstableOrb,
  GiVampireDracula,
  GiVineWhip,
  GiVortex,
  GiWalkingTurret,
  GiWaterDrop,
  GiWaterSplash,
  GiWaveCrest,
  GiWaveStrike,
  GiWerewolf,
  GiWhirlwind,
  GiWindSlap,
  GiWingedScepter,
  GiWingfoot,
  GiWitchFlight,
  GiWizardStaff,
  GiWolfHead,
  GiWolfHowl,
  GiWolfTrap,
  GiWoodenPegleg,
  GiYinYang,
  GiZeusSword,
  GiZigzagHieroglyph,
} from "react-icons/gi";

export const SPELL_ICONS: Readonly<Record<string, IconType>> = {
  "acalmar-emocoes": GiPeaceDove,
  adivinhacao: GiCrystalBall,
  ajuda: GiHeartArmor,
  alarme: GiRingingBell,
  "aliado-planar": GiAngelWings,
  "aljava-veloz": GiQuiver,
  "alterar-forma": GiTransform,
  "alterar-se": GiMirrorMirror,
  amizade: GiShakingHands,
  "amizade-animal": GiPawHeart,
  "ampliar-plantas": GiTreeGrowth,
  "ancora-planar": GiAnchor,
  "andar-na-agua": GiWaterSplash,
  "animar-mortos": GiRaiseZombie,
  "animar-objetos": GiWalkingTurret,
  "antipatia-simpatia": GiOppositeHearts,
  "aprimorar-habilidade": GiMuscleUp,
  aprisionamento: GiImprisoned,
  "arca-secreta-de-leomund": GiLockedChest,
  "area-escorregadia": GiSlippers,
  "arma-elemental": GiFlamingTrident,
  "arma-espiritual": GiSpectre,
  "arma-magica": GiMagicAxe,
  "armadura-arcana": GiMagicShield,
  "armadura-de-agathys": GiIciclesAura,
  arrombar: GiUnlocking,
  "assassino-fantasmagorico": GiDreadSkull,
  "ataque-certeiro": GiOnTarget,
  "ataque-visual": GiEvilEyes,
  augurio: GiStoneTablet,
  "aumentar-reduzir": GiResize,
  "aura-de-pureza": GiAura,
  "aura-de-vida": GiLifeSupport,
  "aura-de-vitalidade": GiHealthNormal,
  "aura-magica-de-nystul": GiBeamsAura,
  "aura-sagrada": GiSunPriest,
  "auxilio-divino": GiWingedScepter,
  banimento: GiCircleCage,
  "banquete-de-herois": GiMeal,
  "barreira-de-laminas": GiSpinningBlades,
  bencao: GiPrayer,
  "boca-encantada": GiLips,
  "bola-de-fogo-controlavel": GiThreeBurningBalls,
  "bom-fruto": GiBerriesBowl,
  "bordao-mistico": GiWizardStaff,
  "bracos-de-hadar": GiTentacleStrike,
  bruxaria: GiWitchFlight,
  "caminhar-em-arvores": GiTreeDoor,
  "caminhar-no-vento": GiWhirlwind,
  "campo-antimagia": GiCancel,
  "cao-fiel-de-mordenkainen": GiSittingDog,
  "carne-para-pedra": GiStoneBust,
  cativar: GiCharm,
  "cegueira-surdez": GiBlindfold,
  "chama-continua": GiCandleFlame,
  "chama-sagrada": GiSunbeams,
  "chicote-de-espinhos": GiVineWhip,
  "chuva-de-meteoros": GiMeteorImpact,
  "circulo-da-morte": GiDeathZone,
  "circulo-de-poder": GiCircleSparks,
  "circulo-de-teletransporte": GiEncirclement,
  "circulo-magico": GiPentagramRose,
  clarividencia: GiThirdEye,
  clone: GiSplitBody,
  "coluna-de-chamas": GiFlameTunnel,
  comando: GiPointing,
  "compreender-idiomas": GiConversation,
  compulsao: GiClawString,
  comunhao: GiPrayerBeads,
  "comunhao-com-a-natureza": GiHolyOak,
  "cone-de-frio": GiIceSpellCast,
  confusao: GiPotionOfMadness,
  "conhecimento-lendario": GiBookAura,
  "conjurar-animais": GiWolfHowl,
  "conjurar-celestial": GiAngelOutfit,
  "conjurar-elementais-menores": GiFireflake,
  "conjurar-elemental": GiRockGolem,
  "conjurar-fada": GiFairy,
  "conjurar-rajada": GiStrikingArrows,
  "conjurar-saraivada": GiArrowsShield,
  "conjurar-seres-da-floresta": GiEntMouth,
  consagrar: GiHolyWater,
  consertar: GiAnvilImpact,
  constricao: GiThornyVine,
  "contato-extraplanar": GiPsychicWaves,
  contingencia: GiTimeTrap,
  contramagica: GiMagicSwirl,
  "controlar-a-agua": GiWaveCrest,
  "controlar-o-clima": GiSunCloud,
  "convocar-familiar": GiOwl,
  "convocar-montaria": GiHorseHead,
  "convocar-relampagos": GiLightningStorm,
  "cordao-de-flechas": GiTargetArrows,
  "coroa-da-loucura": GiCrownedSkull,
  "corrente-de-relampagos": GiChainLightning,
  "crescer-espinhos": GiThornHelix,
  criacao: GiCrystalGrowth,
  "criar-alimentos": GiBread,
  "criar-chamas": GiFlame,
  "criar-mortos-vivos": GiShamblingZombie,
  "criar-ou-destruir-agua": GiWaterDrop,
  "criar-passagem": GiDoorway,
  "cupula-antivida": GiBubbleField,
  "cura-completa": GiHealingShield,
  "cura-completa-em-massa": GiHealthPotion,
  "curar-ferimentos-em-massa": GiNestedHearts,
  "cure-wounds": GiHeartPlus,
  "danca-irresistivel-de-otto": GiMusicalNotes,
  "dedo-da-morte": GiDeathSkull,
  desejo: GiMagicLamp,
  desintegrar: GiDisintegrate,
  despedacar: GiShatteredGlass,
  despertar: GiTreeFace,
  despistar: GiMisdirection,
  "destruicao-banidora": GiDrippingStar,
  "destruicao-cegante": GiSunRadiations,
  "destruicao-colerica": GiAngryEyes,
  "destruicao-estonteante": GiKnockout,
  "destruicao-lancinante": GiFireSilhouette,
  "destruicao-trovejante": GiThunderStruck,
  "detect-magic": GiMagnifyingGlass,
  "detectar-o-bem-e-mal": GiYinYang,
  "detectar-pensamentos": GiBrain,
  "detectar-veneno-e-doenca": GiPoisonBottle,
  "dificultar-deteccao": GiHood,
  "disco-flutuante-de-tenser": GiFloatingPlatforms,
  "disfarcar-se": GiDualityMask,
  "dissipar-magia": GiBrokenShield,
  "dissipar-o-bem-e-mal": GiHolySymbol,
  "doenca-plena": GiDeathJuice,
  "dominar-besta": GiBearHead,
  "dominar-monstro": GiDragonHead,
  "dominar-pessoa": GiPuppet,
  druidismo: GiOakLeaf,
  "duelo-compelido": GiCrossedSwords,
  "encarnacao-fantasmagorica": GiGhost,
  "encontrar-armadilhas": GiWolfTrap,
  "encontrar-o-caminho": GiCompass,
  "enfeiticar-pessoa": GiHeartBeats,
  "enfraquecer-intelecto": GiBrainLeak,
  "enviar-mensagem": GiScrollQuill,
  "escrita-ilusoria": GiQuillInk,
  "escudo-arcano": GiShield,
  "escudo-da-fe": GiTemplarShield,
  "escudo-de-fogo": GiFireShield,
  escuridao: GiMoonBats,
  "esfera-congelante-de-otiluke": GiFrozenOrb,
  "esfera-flamejante": GiFireRing,
  "esfera-resiliente-de-otiluke": GiHolosphere,
  "espada-de-mordenkainen": GiZeusSword,
  "espiritos-guardioes": GiSpiralShell,
  "espirro-acido": GiAcidBlob,
  "esquentar-metal": GiMetalBar,
  estabilizar: GiHeartBattery,
  "explosao-solar": GiSun,
  fabricar: GiAnvil,
  "falar-com-animais": GiWolfHead,
  "falar-com-os-mortos": GiTombstone,
  "falar-com-plantas": GiSprout,
  "fire-bolt": GiBurningDot,
  fireball: GiFireball,
  "flecha-acida-de-melf": GiAcidTube,
  "flecha-relampejante": GiSupersonicArrow,
  "fogo-das-fadas": GiFairyWand,
  "fome-de-hadar": GiVortex,
  "forca-fantasmagorica": GiDread,
  "forjar-morte": GiCrossedBones,
  "forma-eterea": GiFloatingGhost,
  "forma-gasosa": GiDustCloud,
  "formas-animais": GiWerewolf,
  "glifo-de-vigilancia": GiRuneStone,
  "globo-de-invulnerabilidade": GiShieldReflect,
  "globos-de-luz": GiPaperLantern,
  "golpe-constritor": GiGrapple,
  "guardiao-da-fe": GiKnightBanner,
  "healing-word": GiHealing,
  heroismo: GiLaurelCrown,
  identificacao: GiSpyglass,
  idiomas: GiTalk,
  "ilusao-menor": GiMagicHat,
  "ilusao-programada": GiMagickTrick,
  "imagem-maior": GiStarSwirl,
  "imagem-silenciosa": GiEclipse,
  "imobilizar-monstro": GiManacles,
  "imobilizar-pessoa": GiHandcuffs,
  "infligir-ferimentos": GiDrippingKnife,
  "inseto-gigante": GiSpottedBug,
  "inverter-a-gravidade": GiFalling,
  invisibilidade: GiInvisible,
  "invisibilidade-maior": GiInvisibleFace,
  "invocacao-instantanea-de-drawmij": GiGlowingArtifact,
  isolamento: GiCoffin,
  labirinto: GiMaze,
  "lamina-flamejante": GiDrippingSword,
  lentidao: GiSnail,
  "leque-cromatico": GiRainbowStar,
  levitacao: GiLibertyWing,
  "ligacao-telepatica-de-rary": GiHiveMind,
  "limpar-a-mente": GiBrainFreeze,
  "localizar-animais-ou-plantas": GiPlantsAndAnimals,
  "localizar-criatura": GiEyeTarget,
  "localizar-objeto": GiTreasureMap,
  loquacidade: GiSwirlString,
  "lufada-de-vento": GiWindSlap,
  luz: GiLightBulb,
  "luz-do-dia": GiSunrise,
  malogro: GiCursedStar,
  "mansao-magnifica-de-mordenkainen": GiCastle,
  "manto-do-cruzado": GiCape,
  "mao-de-bigby": GiMagicPalm,
  "maos-flamejantes": GiFlamer,
  "maos-magicas": GiHand,
  "marca-da-punicao": GiBrandyBottle,
  "marca-do-cacador": GiHuntingHorn,
  medo: GiScreaming,
  "mensageiro-animal": GiEgyptianBird,
  mensagem: GiSharpLips,
  "mesclar-se-as-rochas": GiStoneBlock,
  metamorfose: GiFrogPrince,
  "metamorfose-verdadeira": GiDna1,
  miragem: GiDesert,
  missao: GiScrollUnfurled,
  "misseis-magicos": GiMissileSwarm,
  "modificar-memoria": GiBrainDump,
  "moldar-rochas": GiStonePile,
  "montaria-fantasmagorica": GiGhostAlly,
  "mover-terra": GiEarthCrack,
  "movimentacao-livre": GiBreakingChain,
  "muralha-de-energia": GiEnergyShield,
  "muralha-de-espinhos": GiSpikedWall,
  "muralha-de-fogo": GiFirewall,
  "muralha-de-gelo": GiIceCube,
  "muralha-de-pedra": GiStoneWall,
  "muralha-de-vento": GiTornado,
  "muralha-prismatica": GiPrism,
  nevasca: GiSnowing,
  "nevoa-fetida": GiPoisonGas,
  "nevoa-mortal": GiPoisonCloud,
  "nevoa-obscurecente": GiFog,
  nublar: GiShadowFollower,
  "nuvem-de-adagas": GiThrownDaggers,
  "nuvem-incendiaria": GiFireWave,
  "olho-arcano": GiEyeball,
  "onda-destrutiva": GiWaveStrike,
  "onda-trovejante": GiSoundWaves,
  "oracao-curativa": GiPrayingMantis,
  "orbe-cromatica": GiUnstableOrb,
  orientacao: GiSpiralArrow,
  "padrao-hipnotico": GiSpiralLollipop,
  "palavra-curativa-em-massa": GiHealthIncrease,
  "palavra-de-poder-atordoar": GiStarStruck,
  "palavra-de-poder-curar": GiShiningHeart,
  "palavra-de-poder-matar": GiSkullCrack,
  "palavra-de-recordacao": GiReturnArrow,
  "palavra-divina": GiHolyGrail,
  "parar-o-tempo": GiStopwatch,
  "passo-nebuloso": GiSmokeBomb,
  "passos-longos": GiWingfoot,
  "passos-sem-pegadas": GiFootprint,
  "patas-de-aranha": GiSpiderAlt,
  "pele-de-arvore": GiWoodenPegleg,
  "pele-de-pedra": GiStonedSkull,
  "pequena-cabana-de-leomund": GiCampingTent,
  perdicao: GiBrokenSkull,
  piscar: GiBoltEye,
  "porta-dimensional": GiMagicGate,
  portal: GiMagicPortal,
  "portal-arcano": GiPortal,
  praga: GiMoebiusTriangle,
  "praga-de-insetos": GiInsectJaws,
  prestidigitacao: GiSparkles,
  "prisao-de-energia": GiCage,
  proibicao: GiStopSign,
  "projecao-astral": GiAstronautHelmet,
  "projetar-imagem": GiShintoShrineMirror,
  "protecao-contra-a-morte": GiLifeInTheBalance,
  "protecao-contra-energia": GiLightningShield,
  "protecao-contra-laminas": GiSwordBreak,
  "protecao-contra-o-bem-e-mal": GiScales,
  "protecao-contra-veneno": GiStandingPotion,
  "proteger-fortaleza": GiLockedFortress,
  "purificar-alimentos": GiFruitBowl,
  "queda-suave": GiFeather,
  "raio-adoecente": GiChemicalBolt,
  "raio-ardente": GiFireRay,
  "raio-de-bruxa": GiBoltSpellCast,
  "raio-de-gelo": GiIceBolt,
  "raio-do-enfraquecimento": GiHealthDecrease,
  "raio-guiador": GiLaserBurst,
  "raio-lunar": GiMoon,
  "raio-solar": GiSunSpear,
  "rajada-de-veneno": GiPoison,
  "rajada-mistica": GiPlasmaBolt,
  "rajada-prismatica": GiStarFormation,
  "recipiente-arcano": GiMagicPotion,
  "recuo-acelerado": GiRun,
  reencarnacao: GiSpiralBloom,
  reflexos: GiDoubleFaceMask,
  regeneracao: GiRegeneration,
  relampago: GiLightningTrio,
  "remover-maldicao": GiCrossedChains,
  "repouso-tranquilo": GiGraveFlowers,
  "repreensao-infernal": GiFireDash,
  resistencia: GiCrossShield,
  "respirar-na-agua": GiBubbles,
  ressurreicao: GiHeartWings,
  "ressurreicao-verdadeira": GiSpikedHalo,
  "restauracao-maior": GiHealthCapsule,
  "restauracao-menor": GiMedicines,
  "reviver-os-mortos": GiRaiseSkeleton,
  revivify: GiLifeBar,
  "riso-histerico-de-tasha": GiTheaterCurtains,
  "rogar-maldicao": GiSkullSignet,
  salto: GiJumpAcross,
  santuario: GiTempleGate,
  "santuario-particular-de-mordenkainen": GiStoneTower,
  "saraivada-de-espinhos": GiThornedArrow,
  semiplano: GiSecretDoor,
  "sentido-bestial": GiDogHouse,
  "servo-invisivel": GiGloves,
  "sexto-sentido": GiAllSeeingEye,
  silencio: GiSilence,
  simbolo: GiZigzagHieroglyph,
  similaridade: GiIronMask,
  simulacro: GiSnowman,
  "sinal-de-esperanca": GiCandleLight,
  sonho: GiDreamCatcher,
  sono: GiSleepy,
  sugestao: GiOilySpiral,
  "sugestao-em-massa": GiRadialBalance,
  "sussurros-dissonantes": GiCrackedMask,
  taumaturgia: GiSparkSpirit,
  teia: GiSpiderWeb,
  telecinesia: GiFloatingCrystal,
  telepatia: GiTelepathy,
  teletransporte: GiTeleport,
  "teletransporte-por-arvores": GiPineTree,
  "tempestade-da-vinganca": GiSandstorm,
  "tempestade-de-fogo": GiFlameSpin,
  "tempestade-de-gelo": GiIceBomb,
  "tentaculos-negros-de-evard": GiTentaclesBarrier,
  terremoto: GiQuakeStomp,
  "terreno-alucinogeno": GiMushroomsCluster,
  "toque-arrepiante": GiSkeletalHand,
  "toque-chocante": GiElectricalResistance,
  "toque-vampirico": GiVampireDracula,
  "tranca-arcana": GiPadlock,
  "truque-de-corda": GiRopeCoil,
  tsunami: GiBigWave,
  velocidade: GiSpeedometer,
  "ver-o-invisivel": GiSemiClosedEye,
  "viagem-planar": GiRingedPlanet,
  videncia: GiCrystalEye,
  "vinculo-protetor": GiChainedHeart,
  "vinha-esmagadora": GiCurlingVines,
  "visao-da-verdade": GiEyeShield,
  "visao-no-escuro": GiNightVision,
  "vitalidade-falsa": GiSkullWithSyringe,
  voo: GiFeatheredWing,
  "zombaria-viciosa": GiImpLaugh,
  "zona-da-verdade": GiJusticeStar,
};
